version: '3'
services:
    redis:
        image: 'redis:3.2.7'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:1.10.1
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - REDIS_PASSWORD=redispass
            - DATA_DIR=/usr/local/airflow/data/
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./dag-requirements.txt:/requirements.txt
            - ./data:/usr/local/airflow/data
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow:1.10.1
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.10.1
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./dag-requirements.txt:/requirements.txt
            - ./data:/usr/local/airflow/data
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: puckel/docker-airflow:1.10.1
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./dag-requirements.txt:/requirements.txt
            - ./data:/usr/local/airflow/data
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - REDIS_PASSWORD=redispass
            - DATA_DIR=/usr/local/airflow/data/
        command: worker
        # deploy:
        #     replicas: 3
        #     resources:
        #         limits:
        #             memory: 16M
        #         reservations:
        #             memory: 16M

    test:
        image: docker-airflow-test:latest
        build:
            context: .
            dockerfile: test.Dockerfile
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./tests:/usr/local/airflow/tests
            - ./data:/usr/local/airflow/data
        command: webserver
        environment:
            - EXECUTOR=Local
            - DATA_DIR=/usr/local/airflow/data/
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
